#!/bin/sh
# Copyright (c) 2011 WorkWare Systems http://www.workware.net.au/
# All rights reserved
# vim:se syntax=tcl:
# \
dir=`dirname "$0"`; exec "`$dir/find-tclsh`" "$0" "$@"

# Dumps the cache in a readable format
if {![file exists .makecache]} {
	puts "No .makecache"
	exit
}
source .makecache

foreach i [lsort [dict keys $tmake(cache)]] {
	lassign [dict get $tmake(cache) $i] vmtime mtime
	if {$mtime == $vmtime} {
		set mtimestr "(same)"
	} else {
		set mtimestr [clock format $mtime -format "%H:%M:%S %d-%b-%Y"]
	}
	puts [format "%25s  V=%s  M=%s" $i [clock format $vmtime -format "%H:%M:%S %d-%b-%Y"] $mtimestr]
}
