#!/bin/sh

c="$1"
i="$2"

echo "In make-two"

# Uncomment this to have time to send SIGINT to test cleanup processing
#sleep 5

echo "Building $c and $i"

echo "#include \"`basename $i`\"" >$c
echo "int main() { return 1; }" >>$c
echo "#define header" >$i

if [ -n "$FAIL" ]; then
	echo 1>&2 "Testing failure"
	exit 1
fi

echo done
