#ifndef _AUTOCONFIG_H
#define _AUTOCONFIG_H
#define FOSSIL_ENABLE_SSL 1
#define HAVE_GETHOSTBYNAME 1
#define HAVE_GETPASS 1
/* #undef HAVE_GETPASSPHRASE */
#define HAVE_INFLATEEND 1
#define HAVE_INT16_T 1
#define HAVE_INTTYPES_H 1
#define HAVE_OPENSSL_SSL_H 1
#define HAVE_PREAD 1
#define HAVE_READLINE 1
#define HAVE_READLINE_READLINE_H 1
#define HAVE_SOCKET 1
#define HAVE_SSL_NEW 1
#define HAVE_STDINT_H 1
#define HAVE_STDIO_H 1
#define HAVE_STDLIB_H 1
#define HAVE_UINT16_T 1
#define HAVE_UINT32_T 1
#define HAVE_UINT8_T 1
#define HAVE_ZLIB_H 1
#define USE_PREAD 1
#define USE_SYSTEM_SQLITE ""
#endif
