# vim:set syntax=tcl:

# If settings.conf doesn't exist, run configure with default options
# If it does, but is out-of-date with respect to auto.def, rerun
# configure with the previous options.
# Note that we don't use $AUTOREMAKE here so that we don't trigger
# an unnecessary build immediately after ./configure due to a different path
Depends {settings.conf jimautoconf.h jim-config.h} auto.def -do {
	note Configure
	run [set AUTOREMAKE] BUILDDIR=$BUILDDIR >$build/config.out
}
Clean config.out

DefaultOptions Executable --nostrip
DefaultOptions SharedLib --strip
DefaultOptions SharedObject --strip

# settings.conf is generated by configure (autosetup)
Load settings.conf
define? AUTOREMAKE configure
